# This file is part of Beard.
# Copyright (C) 2014 CERN.
#
# Beard is a free software; you can redistribute it and/or modify it
# under the terms of the Revised BSD License; see LICENSE file for
# more details.

language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy python-scipy

install:
    - pip install coveralls pep257
    - pip install pytest pytest-pep8 pytest-cov pytest-cache sphinx

script:
    - pep257 beard
    - "sphinx-build -qnNW doc doc/_build/html"
    - python setup.py test

after_success:
    - coveralls

notifications:
    email: false
